### ISSUE TITLE
I have queries

### ISSUE THREAD

**Issue by boneskull** [MylesBorins/conference-proposals#1]
- Have all of these proposals been accepted?  
  - If so, what of the proposals that didn't get accepted? 
  - Are they worth posting? 
  - If not, Do you have examples of poor CFP's?

How many times was each talk given? Which talks are most popular, etc?

**Comment by boneskull** [comment]
formatting fail. you get the idea

**Comment by MylesBorins** [comment]
hey @boneskull 

* Not all talks have been accepted
* every talks that has been accepted includes links to the presentation online
* ATM I don't really have any cfps that I don't view as worth posting. I have a new ideas folder for sketches, and would likely make a "retired folder" when I no longer give a talk. I have yet to come up with a CFP that I have given up on, I generally rework and submit to other events
* Most popular talk by far was "Node.js Versions", followed by "A Distributed Orchestra"

**Comment by boneskull** [comment]
tyvm!
